version: '3'
services:
  io7api:
    container_name: io7api
    image: mynode
    environment:
      - CAFILE=iothub.crt
      - ADMIN_ID=admin
      - ADMIN_PASSWORD=iot107
      - MQTT_CONN=mqtts://192.168.72.143
      #- DYNSEC_FILE=mqtt/dynamic-security.json
    volumes:
      - /home/pi/data/io7api:/home/node/app
      - /home/pi/data/mosquitto/config/:/home/node/app/mqtt
    ports:
      - "2009:2009"
    restart: always
